### ISSUE TITLE
VEC_SLO has an error in description about the location of the shift amount

### ISSUE THREAD

**Issue by cjashfor** [OpenPOWERFoundation/ELFv2-ABI#104]
The description has this text:
Result value:
The result is the contents of ARG1, shifted left by the number of bytes specified by the
most-significant nibble of the least-significant byte of ARG2. The bits that are shifted out
are replaced by zeros.

And there's a note that says: "That is, by little-endian bits 7–4 or big-endian bits 121–124."

There's a contradiction, though, because bits 121-124 are not the upper nibble, which would be 120-123.  I verified through debugging my code which uses this instruction that 121-124 are the correct bit numbers.

The sister function - VEC_SRO -  description does not contain this error.

**Comment by wschmidt-ibm** [comment]
This is already fixed in the PVIPR document that will replace this appendix.  That says:

"Vector r receives the contents of a, shifted left by the number of bytes specified by
bits 1:4 of the least-significant byte of b."

Since this Appendix will be deleted in the next version, I'm closing this as fix-available.
